extraction:
  cpp:
    after_prepare: 
      - python report.py 89
  cobol:
    after_prepare: 
      - python report.py 89
  csharp:
    after_prepare: 
      - python report.py 89
  java:
    after_prepare: 
      - python report.py 89
  javascript:
    after_prepare: 
      - python report.py 89
  python:
    after_prepare: 
      - python report.py 89
